---
language: go
go:
- 1.15.x
services:
- docker
cache:
  directories:
  - $GOPATH/pkg/mod
  - $HOME/.cache/go-build
script:
- make docker.build
deploy:
- provider: script
  skip_cleanup: true
  script: make docker.push
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
